-- Drop all tables to reset database
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS boarding_passes;
DROP TABLE IF EXISTS baggage;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS passengers;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS flight_seats;
DROP TABLE IF EXISTS flights;
DROP TABLE IF EXISTS seats;
DROP TABLE IF EXISTS airports;
DROP TABLE IF EXISTS airplanes;
DROP TABLE IF EXISTS airlines;
DROP TABLE IF EXISTS cities;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS SequelizeMeta;

SET FOREIGN_KEY_CHECKS = 1;
